### ISSUE TITLE
2nd Movie Field won't collapse in Web UI

### ISSUE THREAD

**Issue by jjnether** [LizardByte/Themerr-plex#255]
### Describe the Bug

When trying to collapse the 2nd movies field for my 2nd movies library, it won't collapse. The first field collapses fine though. I can hit the arrow and it changes directions, but doesn't collapse it. Note that I have no themes for this library. See picture below:

![example](https://github.com/LizardByte/Themerr-plex/assets/88998541/5e5a74ef-b294-41d8-950a-deadce34fc95)

### Expected Behavior

I expect that when I hit the arrow, it should collapse the whole movies field similar to the top movies field

**Comment by ReenigneArcher** [comment]
I'm not sure what the issue is on this. I can't reproduce it.

- Are there any errors in developer tools of your browser?
- Is it possible you have multiple libraries with the same name?

The collapse/expand is handled by bootstrap.

Could you try these steps? (all config/settings will be retained)

- Stop Plex app/service
- Delete Themerr-plex.bundle from plugins directory
- Re-install Themerr-plex plugin
- Start Plex app/service

Do you have the same issue?

**Comment by ReenigneArcher** [comment]
When you get a chance, please test #268
