### ISSUE TITLE
Same movie in multiple libraries will show "failed to download"

### ISSUE THREAD

**Issue by Duglim** [LizardByte/Themerr-plex#354]
### Describe the Bug

If a movie is present in multiple libraries, it will only show up as green "Themerr provided" in the first Library. While the theme is also playing in all other libraries, they flag it a "failed to download".

A common case to have a movie multiple times is different libraries for "Movies" and "4K Movies". Internally they share the same metadata, since the movie is the same. 

Log exerpt:
```
DEBUG (plex_api_helper:114) - item title: Star Trek (4K UHD)
DEBUG (plex_api_helper:185) - Not overwriting locked theme for movie: Star Trek (4K UHD)
```

### Expected Behavior

If a theme is already available, show it as green "Themerr provided" in the Web UI.

**Comment by ReenigneArcher** [comment]
According to the logs you provided... The theme is locked, so it won't be overwritten. There's a setting to allow ignoring the lock.

It's nothing to do with the same movie being in multiple libraries. Themerr doesn't care about that or keep track of it in any way.

**Comment by ReenigneArcher** [comment]
When you manually change a poster (for example), that poster will be locked.

In the early days of Themerr, every theme was locked by default. In a recent version of Themerr we started unlocking themes... but themes that were already locked by Themerr would not be updated.

So if you have never gotten themes from anywhere except themerr, it's safe to overwrite locked themes.

**Comment by ReenigneArcher** [comment]
> I assume, having multiple libraries with same movies has some interferences.

It doesn't. We work with the rating key of each item, which is unique.

I suspect this is actually related to #323

**Comment by ReenigneArcher** [comment]
Could you test the build from https://github.com/LizardByte/Themerr-plex/actions/runs/8089835832?pr=356 ?

You need to be logged into to GitHub in order to download the artifacts.

**Comment by ReenigneArcher** [comment]
Closing due to no response.

**Comment by ReenigneArcher** [comment]
I need a reproduction example, as I can't reproduce this... and it doesn't make sense because every item in Plex gets a different rating key, even if they are the "same" movie... according to Plex they are not the same. Themerr works with the rating key as well.

You can see below, I have the same movies in 3 different libraries... they all work. We also unit test this.

![image](https://github.com/LizardByte/Themerr-plex/assets/42013603/9fd037cd-d9d2-4621-9836-1f216c2ce0a7)

![image](https://github.com/LizardByte/Themerr-plex/assets/42013603/f275b7bf-a128-42f6-9085-63acb17c1795)

![image](https://github.com/LizardByte/Themerr-plex/assets/42013603/94626d7e-d4b0-44a8-9e06-0a22faff900e)

**Comment by ReenigneArcher** [comment]
I can't read that language. Show it in English.

**Comment by ReenigneArcher** [comment]
Glad it's working!

> Just needed to run the "update metatdata" in Plex again.

This isn't really necessary (depending on your config options)... it will themes and the UI cache update on a schedule. Default is every 1 hour.
